export const COUNTRIES = [
  { name: "السودان", code: "SD", dial: "+249" },
  { name: "مصر", code: "EG", dial: "+20" },
  { name: "المملكة العربية السعودية", code: "SA", dial: "+966" },
  { name: "الإمارات العربية المتحدة", code: "AE", dial: "+971" },
  { name: "قطر", code: "QA", dial: "+974" },
  { name: "الكويت", code: "KW", dial: "+965" },
  { name: "البحرين", code: "BH", dial: "+973" },
  { name: "عمان", code: "OM", dial: "+968" },
  { name: "الأردن", code: "JO", dial: "+962" },
  { name: "العراق", code: "IQ", dial: "+964" },
  { name: "لبنان", code: "LB", dial: "+961" },
  { name: "فلسطين", code: "PS", dial: "+970" },
  { name: "سوريا", code: "SY", dial: "+963" },
  { name: "اليمن", code: "YE", dial: "+967" },
  { name: "ليبيا", code: "LY", dial: "+218" },
  { name: "تونس", code: "TN", dial: "+216" },
  { name: "الجزائر", code: "DZ", dial: "+213" },
  { name: "المغرب", code: "MA", dial: "+212" },
  { name: "موريتانيا", code: "MR", dial: "+222" },
  { name: "الصومال", code: "SO", dial: "+252" },
  { name: "جيبوتي", code: "DJ", dial: "+253" },
  { name: "جزر القمر", code: "KM", dial: "+269" },
  { name: "تشاد", code: "TD", dial: "+235" },
  { name: "نيجيريا", code: "NG", dial: "+234" },
  { name: "غانا", code: "GH", dial: "+233" },
  { name: "كينيا", code: "KE", dial: "+254" },
  { name: "إثيوبيا", code: "ET", dial: "+251" },
  { name: "إريتريا", code: "ER", dial: "+291" },
  { name: "جنوب السودان", code: "SS", dial: "+211" },
  { name: "أوغندا", code: "UG", dial: "+256" },
  { name: "تنزانيا", code: "TZ", dial: "+255" },
  { name: "رواندا", code: "RW", dial: "+250" },
  { name: "بوروندي", code: "BI", dial: "+257" },
  { name: "جمهورية الكونغو الديمقراطية", code: "CD", dial: "+243" },
  { name: "الكونغو", code: "CG", dial: "+242" },
  { name: "الكاميرون", code: "CM", dial: "+237" },
  { name: "الغابون", code: "GA", dial: "+241" },
  { name: "غينيا الاستوائية", code: "GQ", dial: "+240" },
  { name: "السنغال", code: "SN", dial: "+221" },
  { name: "مالي", code: "ML", dial: "+223" },
  { name: "بوركينا فاسو", code: "BF", dial: "+226" },
  { name: "النيجر", code: "NE", dial: "+227" },
  { name: "بنين", code: "BJ", dial: "+229" },
  { name: "توغو", code: "TG", dial: "+228" },
  { name: "ساحل العاج", code: "CI", dial: "+225" },
  { name: "غينيا", code: "GN", dial: "+224" },
  { name: "غينيا بيساو", code: "GW", dial: "+245" },
  { name: "ليبيريا", code: "LR", dial: "+231" },
  { name: "سيراليون", code: "SL", dial: "+232" },
  { name: "غامبيا", code: "GM", dial: "+220" },
  { name: "إفريقيا الوسطى", code: "CF", dial: "+236" },
  { name: "أنغولا", code: "AO", dial: "+244" },
  { name: "زامبيا", code: "ZM", dial: "+260" },
  { name: "زيمبابوي", code: "ZW", dial: "+263" },
  { name: "موزامبيق", code: "MZ", dial: "+258" },
  { name: "مالاوي", code: "MW", dial: "+265" },
  { name: "مدغشقر", code: "MG", dial: "+261" },
  { name: "بوتسوانا", code: "BW", dial: "+267" },
  { name: "ناميبيا", code: "NA", dial: "+264" },
  { name: "جنوب إفريقيا", code: "ZA", dial: "+27" },
  { name: "ليسوتو", code: "LS", dial: "+266" },
  { name: "إسواتيني", code: "SZ", dial: "+268" },
  { name: "موريشيوس", code: "MU", dial: "+230" },
  { name: "سيشل", code: "SC", dial: "+248" },
  { name: "تركيا", code: "TR", dial: "+90" },
  { name: "المملكة المتحدة", code: "GB", dial: "+44" },
  { name: "الولايات المتحدة", code: "US", dial: "+1" },
  { name: "كندا", code: "CA", dial: "+1" },
  { name: "أستراليا", code: "AU", dial: "+61" },
  { name: "ألمانيا", code: "DE", dial: "+49" },
  { name: "فرنسا", code: "FR", dial: "+33" },
  { name: "إيطاليا", code: "IT", dial: "+39" },
  { name: "إسبانيا", code: "ES", dial: "+34" },
  { name: "هولندا", code: "NL", dial: "+31" },
  { name: "بلجيكا", code: "BE", dial: "+32" },
  { name: "النمسا", code: "AT", dial: "+43" },
  { name: "السويد", code: "SE", dial: "+46" },
  { name: "النرويج", code: "NO", dial: "+47" },
  { name: "الدنمارك", code: "DK", dial: "+45" },
  { name: "فنلندا", code: "FI", dial: "+358" },
  { name: "اليونان", code: "GR", dial: "+30" },
  { name: "سويسرا", code: "CH", dial: "+41" },
  { name: "ماليزيا", code: "MY", dial: "+60" },
  { name: "إندونيسيا", code: "ID", dial: "+62" },
  { name: "باكستان", code: "PK", dial: "+92" },
  { name: "بنغلاديش", code: "BD", dial: "+880" },
  { name: "الهند", code: "IN", dial: "+91" },
  { name: "الصين", code: "CN", dial: "+86" },
  { name: "اليابان", code: "JP", dial: "+81" },
  { name: "كوريا الجنوبية", code: "KR", dial: "+82" },
  { name: "سنغافورة", code: "SG", dial: "+65" },
  { name: "تايلاند", code: "TH", dial: "+66" },
  { name: "روسيا", code: "RU", dial: "+7" },
  { name: "أوكرانيا", code: "UA", dial: "+380" },
  { name: "بولندا", code: "PL", dial: "+48" },
  { name: "رومانيا", code: "RO", dial: "+40" },
  { name: "بلغاريا", code: "BG", dial: "+359" },
  { name: "المجر", code: "HU", dial: "+36" },
  { name: "جمهورية التشيك", code: "CZ", dial: "+420" },
  { name: "سلوفاكيا", code: "SK", dial: "+421" },
  { name: "كرواتيا", code: "HR", dial: "+385" },
  { name: "صربيا", code: "RS", dial: "+381" },
  { name: "البوسنة والهرسك", code: "BA", dial: "+387" },
  { name: "ألبانيا", code: "AL", dial: "+355" },
] as const

/** Just the country names (for forms that only need names) */
export const COUNTRY_NAMES: readonly string[] = COUNTRIES.map((c) => c.name)

export const FACULTIES = [
  "كلية الطب",
  "كلية طب الفم والأسنان",
  "كلية الصيدلة",
  "كلية علوم المختبرات",
  "كلية علوم التمريض",
  "كلية الهندسة",
  "كلية دراسات الحاسوب",
  "كلية العلوم البحتة والتطبيقية",
  "كلية تقانة الإنتاج والتصنيع الزراعي",
  "كلية المعادن والنفط",
  "كلية التربية",
  "كلية الشريعة والقانون",
  "كلية الاقتصاد والعلوم السياسية",
  "كلية الآداب",
  "كلية الإعلام",
  "كلية العلوم الإدارية",
  "كلية اللغة العربية",
  "كلية الألسن",
  "كلية دراسات الكوارث والأمن الإنساني",
  "كلية العلوم الأسرية وتنمية المجتمع",
  "كلية الدراسات الإسلامية",
  "كلية القرآن الكريم وعلومه",
]

export const UNIVERSITIES = [
  "جامعة إفريقيا العالمية",
  "جامعة الخرطوم",
  "جامعة السودان للعلوم والتكنولوجيا",
  "جامعة النيلين",
  "جامعة الرباط الوطني",
  "جامعة كرري",
  "جامعة أم درمان الإسلامية",
  "جامعة الجزيرة",
  "جامعة بحري",
  "جامعة سنار",
  "جامعة كسلا",
  "جامعة القضارف",
  "جامعة دنقلا",
  "جامعة غرب كردفان",
  "جامعة الملك سعود",
  "جامعة القاهرة",
  "جامعة عين شمس",
  "جامعة الإسكندرية",
  "أخرى",
]

export const DEGREES = ["دبلوم", "بكالوريوس", "ماجستير", "دكتوراه", "دبلوم عالي"]
export const SECTORS = ["حكومي", "خاص", "غير ربحي", "أكاديمي", "حر", "أخرى"]
export const GENDERS = ["ذكر", "أنثى"]
export const MEMBERSHIP_TYPES = ["عضو عامل", "عضو منتسب", "عضو فخري", "عضو داعم"]
