import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

const pageContents = [
  // ═══════════════════════════════════════════════
  // HOME PAGE
  // ═══════════════════════════════════════════════
  { page: "home", section: "hero", key: "title", valueAr: "رابطة خريجي جامعة أفريقيا العالمية", valueEn: "Association of IUA Graduates" },
  { page: "home", section: "hero", key: "subtitle", valueAr: "نجمع الخريجين لبناء مستقبل أفضل وتعزيز الروابط المهنية والأكاديمية", valueEn: "Uniting graduates for a better future and strengthening professional and academic bonds" },
  { page: "home", section: "hero", key: "button1_text", valueAr: "انضم إلينا", valueEn: "Join Us" },
  { page: "home", section: "hero", key: "button2_text", valueAr: "اعرف المزيد", valueEn: "Learn More" },
  { page: "home", section: "stats", key: "members_label", valueAr: "عضو مسجل", valueEn: "Registered Members" },
  { page: "home", section: "stats", key: "events_label", valueAr: "حدث وفعالية", valueEn: "Events & Activities" },
  { page: "home", section: "stats", key: "projects_label", valueAr: "مشروع تنفيذي", valueEn: "Implemented Projects" },
  { page: "home", section: "stats", key: "years_label", valueAr: "سنوات من العطاء", valueEn: "Years of Giving" },
  { page: "home", section: "news", key: "title", valueAr: "آخر الأخبار", valueEn: "Latest News" },
  { page: "home", section: "news", key: "read_more", valueAr: "اقرأ المزيد", valueEn: "Read More" },
  { page: "home", section: "news", key: "view_all", valueAr: "عرض جميع الأخبار", valueEn: "View All News" },
  { page: "home", section: "gallery", key: "title", valueAr: "معرض الصور", valueEn: "Photo Gallery" },
  { page: "home", section: "gallery", key: "subtitle", valueAr: "لحظات لا تُنسى من أحداثنا وأنشطتنا", valueEn: "Unforgettable moments from our events and activities" },
  { page: "home", section: "gallery", key: "view_all", valueAr: "عرض المعرض كاملاً", valueEn: "View Full Gallery" },
  { page: "home", section: "events", key: "title", valueAr: "الأحداث القادمة", valueEn: "Upcoming Events" },
  { page: "home", section: "events", key: "view_all", valueAr: "عرض جميع الأحداث", valueEn: "View All Events" },
  { page: "home", section: "events", key: "status_active", valueAr: "نشط", valueEn: "Active" },
  { page: "home", section: "events", key: "status_completed", valueAr: "مكتمل", valueEn: "Completed" },
  { page: "home", section: "events", key: "status_upcoming", valueAr: "قادم", valueEn: "Upcoming" },
  { page: "home", section: "events", key: "status_ongoing", valueAr: "جاري", valueEn: "Ongoing" },
  { page: "home", section: "projects", key: "title", valueAr: "المشاريع المميزة", valueEn: "Featured Projects" },
  { page: "home", section: "projects", key: "view_all", valueAr: "عرض جميع المشاريع", valueEn: "View All Projects" },
  { page: "home", section: "cta", key: "title", valueAr: "انضم إلى عائلة الرابطة", valueEn: "Join the Association Family" },
  { page: "home", section: "cta", key: "subtitle", valueAr: "كن جزءاً من مجتمع خريجي جامعة أفريقيا العالمية", valueEn: "Be part of the IUA graduates community" },
  { page: "home", section: "cta", key: "membership_button", valueAr: "طلب عضوية", valueEn: "Apply for Membership" },
  { page: "home", section: "cta", key: "donate_button", valueAr: "تبرع الآن", valueEn: "Donate Now" },
  { page: "home", section: "contact", key: "address_label", valueAr: "العنوان", valueEn: "Address" },
  { page: "home", section: "contact", key: "address_value", valueAr: "الخرطوم - السودان", valueEn: "Khartoum - Sudan" },
  { page: "home", section: "contact", key: "phone_label", valueAr: "الهاتف", valueEn: "Phone" },
  { page: "home", section: "contact", key: "phone_value", valueAr: "+249114210853", valueEn: "+249114210853" },
  { page: "home", section: "contact", key: "email_label", valueAr: "البريد الإلكتروني", valueEn: "Email" },
  { page: "home", section: "contact", key: "email_value", valueAr: "aiuagho@gmail.com", valueEn: "aiuagho@gmail.com" },

  // ═══════════════════════════════════════════════
  // ABOUT PAGE
  // ═══════════════════════════════════════════════
  { page: "about", section: "hero", key: "title", valueAr: "من نحن", valueEn: "About Us" },
  { page: "about", section: "hero", key: "subtitle", valueAr: "تعرف على رؤيتنا ومهمتنا وأهدافنا وتاريخنا في رابطة خريجي الجامعة الدولية الأفريقية", valueEn: "Discover our vision, mission, objectives, and history at the Africa International University Alumni Association" },
  { page: "about", section: "hero", key: "badge_text", valueAr: "رابطة خريجي الجامعة الدولية الأفريقية", valueEn: "AIUAG Alumni Association" },
  { page: "about", section: "hero", key: "explore_button", valueAr: "ابدأ الاستكشاف", valueEn: "Start Exploring" },
  { page: "about", section: "tabs", key: "who_we_are", valueAr: "من نحن", valueEn: "Who We Are" },
  { page: "about", section: "tabs", key: "vision", valueAr: "رؤيتنا", valueEn: "Our Vision" },
  { page: "about", section: "tabs", key: "mission", valueAr: "مهمتنا", valueEn: "Our Mission" },
  { page: "about", section: "tabs", key: "objectives", valueAr: "أهدافنا", valueEn: "Our Objectives" },
  { page: "about", section: "tabs", key: "history", valueAr: "تاريخنا", valueEn: "Our History" },
  { page: "about", section: "about", key: "section_label", valueAr: "تعرف علينا", valueEn: "Who We Are" },
  { page: "about", section: "about", key: "title", valueAr: "عن الرابطة", valueEn: "About the Association" },
  { page: "about", section: "about", key: "description_1", valueAr: "رابطة خريجي الجامعة الدولية الأفريقية (AIUAG) هي منظمة غير ربحية تأسست عام 2013 بمدينة الخرطوم بالسودان، بهدف ربط خريجي الجامعة الدولية الأفريقية وتعزيز الروابط المهنية والاجتماعية بينهم.", valueEn: "The Africa International University Alumni Association (AIUAG) is a non-profit organization established in 2013 in Khartoum, Sudan, with the aim of connecting graduates and strengthening professional and social ties among them." },
  { page: "about", section: "about", key: "description_2", valueAr: "منذ تأسيسها، قامت الرابطة بتنظيم أكثر من 50 فعالية ومؤتمر، وتمكين آلاف الخريجين من خلال برامج الإرشاد والتدريب وفرص العمل.", valueEn: "Since its establishment, the association has organized more than 50 events and conferences, and empowered thousands of graduates through mentoring, training, and career opportunities." },
  { page: "about", section: "about", key: "description_3", valueAr: "تؤمن الرابطة بأن الخريجين هم سفراء الجامعة وأعمدة المجتمع، وأن تعزيز الروابط بينهم يسهم في التنمية المستدامة.", valueEn: "The association believes that graduates are ambassadors of the university and pillars of society, and that strengthening bonds among them contributes to sustainable development." },
  { page: "about", section: "stats", key: "founding_year", valueAr: "2013", valueEn: "2013" },
  { page: "about", section: "stats", key: "founding_year_label", valueAr: "سنة التأسيس", valueEn: "Year Founded" },
  { page: "about", section: "stats", key: "members_count", valueAr: "5,000+", valueEn: "5,000+" },
  { page: "about", section: "stats", key: "members_count_label", valueAr: "عضو", valueEn: "Members" },
  { page: "about", section: "stats", key: "events_count", valueAr: "50+", valueEn: "50+" },
  { page: "about", section: "stats", key: "events_count_label", valueAr: "فعالية", valueEn: "Events" },
  { page: "about", section: "stats", key: "projects_count", valueAr: "20+", valueEn: "20+" },
  { page: "about", section: "stats", key: "projects_count_label", valueAr: "مشروع", valueEn: "Projects" },
  { page: "about", section: "vision", key: "section_label", valueAr: "إلى أين نسير", valueEn: "Where We're Going" },
  { page: "about", section: "vision", key: "title", valueAr: "رؤيتنا", valueEn: "Our Vision" },
  { page: "about", section: "vision", key: "statement", valueAr: "أن نكون الرابطة الرائدة في إفريقيا لخدمة الخريجين والمجتمع", valueEn: "To be the leading alumni association in Africa serving graduates and the community" },
  { page: "about", section: "vision", key: "item1_title", valueAr: "الريادة", valueEn: "Leadership" },
  { page: "about", section: "vision", key: "item1_desc", valueAr: "أن نكون الرابطة الرائدة في إفريقيا، معترفاً بتأثيرنا وابتكارنا والالتزامنا بالتميز في خدمة الخريجين والمجتمع.", valueEn: "To be the leading alumni association in Africa, recognized for our impact, innovation, and commitment to excellence in serving graduates and the community." },
  { page: "about", section: "vision", key: "item2_title", valueAr: "التواصل", valueEn: "Connection" },
  { page: "about", section: "vision", key: "item2_desc", valueAr: "بناء شبكة لا تنفصل من المحترفين تتجاوز الحدود والثقافات والصناعات في جميع أنحاء القارة الأفريقية.", valueEn: "Building an unbreakable network of professionals that transcends borders, cultures, and industries across Africa." },
  { page: "about", section: "vision", key: "item3_title", valueAr: "الابتكار", valueEn: "Innovation" },
  { page: "about", section: "vision", key: "item3_desc", valueAr: "تعزيز ثقافة الابتكار وريادة الأعمال بين الخريجين، ودفع عجلة النمو الاقتصادي والتنمية الاجتماعية.", valueEn: "Fostering a culture of innovation and entrepreneurship among alumni, driving economic growth and social development." },
  { page: "about", section: "vision", key: "item4_title", valueAr: "التنمية", valueEn: "Development" },
  { page: "about", section: "vision", key: "item4_desc", valueAr: "المساهمة في أهداف التنمية المستدامة في أفريقيا من خلال التعليم والإرشاد وخدمة المجتمع.", valueEn: "Contributing to sustainable development goals across Africa through education, mentorship, and community service." },
  { page: "about", section: "mission", key: "section_label", valueAr: "كيف نعمل", valueEn: "How We Work" },
  { page: "about", section: "mission", key: "title", valueAr: "مهمتنا", valueEn: "Our Mission" },
  { page: "about", section: "mission", key: "statement", valueAr: "توفير بيئة محفزة تجمع الخريجين وتعزز الروابط المهنية والاجتماعية بينهم", valueEn: "To provide a stimulating environment that brings together alumni and strengthens professional and social ties" },
  { page: "about", section: "mission", key: "item1_title", valueAr: "التواصل والشبكات", valueEn: "Connect & Network" },
  { page: "about", section: "mission", key: "item1_desc", valueAr: "بناء وaintenance شبكات مهنية قوية بين الخريجين، وتوفير منصات تفاعلية لتبادل الخبرات والأفكار.", valueEn: "Building and maintaining strong professional networks among graduates, and providing interactive platforms for exchanging expertise and ideas." },
  { page: "about", section: "mission", key: "item2_title", valueAr: "التطوير والتمكين", valueEn: "Develop & Empower" },
  { page: "about", section: "mission", key: "item2_desc", valueAr: "توفير فرص التطوير المهني المستمر من خلال البرامج التدريبية والورش_work والمحاضرات.", valueEn: "Providing continuous professional development opportunities through training programs, workshops, and lectures." },
  { page: "about", section: "mission", key: "item3_title", valueAr: "الخدمة والدعم", valueEn: "Serve & Support" },
  { page: "about", section: "mission", key: "item3_desc", valueAr: "دعم تطوير الجامعة وخدمة المجتمع السوداني من خلال مشاريع تنموية وומבادرات مجتمعية.", valueEn: "Supporting the university development and serving the Sudanese community through developmental projects and community initiatives." },
  { page: "about", section: "mission", key: "item4_title", valueAr: "الابتكار والقيادة", valueEn: "Innovate & Lead" },
  { page: "about", section: "mission", key: "item4_desc", valueAr: "تعزيز الابتكار والقيادة بين الخريجين، وتحفيز ريادة الأعمال والأثر الإيجابي في المجتمع.", valueEn: "Fostering innovation and leadership among alumni, and motivating entrepreneurship and positive community impact." },
  { page: "about", section: "objectives", key: "section_label", valueAr: "ما نسعى لتحقيقه", valueEn: "What We Aim For" },
  { page: "about", section: "objectives", key: "title", valueAr: "أهدافنا", valueEn: "Our Objectives" },
  { page: "about", section: "objectives", key: "item1_title", valueAr: "توحيد الخريجين تحت مظلة منظمة", valueEn: "Unite Alumni Under One Organization" },
  { page: "about", section: "objectives", key: "item1_desc", valueAr: "توحيد جميع خريجي الجامعة الدولية الأفريقية تحت مظلة منظمة واحدة تعزز الروابط والمصالح المشتركة.", valueEn: "To unite all graduates under one umbrella organization that strengthens bonds and shared interests." },
  { page: "about", section: "objectives", key: "item2_title", valueAr: "دعم مشاريع تطوير الجامعة", valueEn: "Support University Development" },
  { page: "about", section: "objectives", key: "item2_desc", valueAr: "المساهمة الفعّالة في دعم مشاريع التحسين في الجامعة وتعزيز مكانتها الأكاديمية.", valueEn: "To actively contribute to development projects at the university and enhance its academic standing." },
  { page: "about", section: "objectives", key: "item3_title", valueAr: "تنظيم فعاليات ومؤتمرات", valueEn: "Organize Events and Conferences" },
  { page: "about", section: "objectives", key: "item3_desc", valueAr: "تنظيم لقاءات منتظمة للخريجين ومؤتمرات مهنية تناقش قضايا المجتمع والتنمية.", valueEn: "To organize regular alumni gatherings and professional conferences that address community and development issues." },
  { page: "about", section: "objectives", key: "item4_title", valueAr: "بناء شراكات دولية", valueEn: "Build International Partnerships" },
  { page: "about", section: "objectives", key: "item4_desc", valueAr: "إنشاء شراكات استراتيجية مع جمعيات الخريجين الدولية لتبادل الخبرات وال_best practices.", valueEn: "To establish strategic partnerships with international alumni associations for exchanging expertise and best practices." },
  { page: "about", section: "objectives", key: "item5_title", valueAr: "إنشاء قاعدة بيانات للخريجين", valueEn: "Create Alumni Database" },
  { page: "about", section: "objectives", key: "item5_desc", valueAr: "تطوير وإدارة قاعدة بيانات شاملة للخريجين تسهل التواصل وتبادل المعلومات.", valueEn: "To develop and maintain a comprehensive alumni database that facilitates communication and information exchange." },
  { page: "about", section: "objectives", key: "item6_title", valueAr: "نشر التقارير والأبحاث", valueEn: "Publish Reports and Research" },
  { page: "about", section: "objectives", key: "item6_desc", valueAr: "إعداد ونشر تقارير منتظمة وأوراق بحثية حول قضايا الخريجين والمجتمع.", valueEn: "To produce and publish regular reports and research papers on alumni and community issues." },
  { page: "about", section: "objectives", key: "item7_title", valueAr: "تسهيل التطوير المهني", valueEn: "Facilitate Professional Development" },
  { page: "about", section: "objectives", key: "item7_desc", valueAr: "توفير موارد التطوير المهني وبرامج الإرشاد لمساعدة الخريجين على النجاح في مساراتهم.", valueEn: "To provide career development resources and mentoring programs to help graduates succeed in their paths." },
  { page: "about", section: "objectives", key: "item8_title", valueAr: "خدمة المجتمع السوداني", valueEn: "Serve the Sudanese Community" },
  { page: "about", section: "objectives", key: "item8_desc", valueAr: "المشاركة في أنشطة خدمة المجتمع والمساهمة في التنمية المستدامة في السودان.", valueEn: "To engage in community service activities and contribute to sustainable development in Sudan." },
  { page: "about", section: "history", key: "section_label", valueAr: "رحلتنا عبر الزمن", valueEn: "Our Journey" },
  { page: "about", section: "history", key: "title", valueAr: "تاريخنا", valueEn: "Our History" },
  { page: "about", section: "history", key: "year2013_title", valueAr: "تأسيس الرابطة", valueEn: "Association Founded" },
  { page: "about", section: "history", key: "year2013_desc", valueAr: "تم تأسيس رابطة خريجي الجامعة الدولية الأفريقية رسمياً في الخرطوم بهدف ربط الخريجين وخدمة المجتمع.", valueEn: "The AIUAG was officially established in Khartoum to connect graduates and serve the community." },
  { page: "about", section: "history", key: "year2015_title", valueAr: "أول مؤتمر للخريجين", valueEn: "First Alumni Conference" },
  { page: "about", section: "history", key: "year2015_desc", valueAr: "أُقيم أول مؤتمر للخريجين، حيث شهد حضور أكثر من 500 خريج من مختلف أنحاء السودان.", valueEn: "The first alumni conference was held, bringing together over 500 graduates from across Sudan." },
  { page: "about", section: "history", key: "year2018_title", valueAr: "إطلاق برنامج الإرشاد", valueEn: "Mentoring Program Launch" },
  { page: "about", section: "history", key: "year2018_desc", valueAr: "أطلقت الرابطة برنامجها الرئيسي للإرشاد الذي يربط الخريجين القدامى بالجدد.", valueEn: "The association launched its flagship mentoring program connecting senior graduates with newcomers." },
  { page: "about", section: "history", key: "year2020_title", valueAr: "توسيع العضوية", valueEn: "Membership Expansion" },
  { page: "about", section: "history", key: "year2020_desc", valueAr: "وسعت الرابطة عضويتها لتتجاوز 3000 عضو مسجل من مختلف الكليات والتخصصات.", valueEn: "The association expanded its membership to over 3,000 registered members from various faculties and specialties." },
  { page: "about", section: "history", key: "year2023_title", valueAr: "المؤتمر الخامس", valueEn: "5th Conference" },
  { page: "about", section: "history", key: "year2023_desc", valueAr: "كان المؤتمر الخامس هو الأكبر حتى الآن، حيث حضره أكثر من 1000 خريج ومضيف.", valueEn: "The 5th alumni conference was the largest yet, attended by over 1,000 graduates and guests." },
  { page: "about", section: "history", key: "year2025_title", valueAr: "ملتقى أفريقيا للتنمية", valueEn: "Africa Development Forum" },
  { page: "about", section: "history", key: "year2025_desc", valueAr: "نظّمت الرابطة الملتقى الأول لأفريقيا للتنمية بمشاركة خبراء دوليين.", valueEn: "The association organized the inaugural Africa Development Forum with international experts." },
  { page: "about", section: "history", key: "year2026_title", valueAr: "التوسع الإقليمي", valueEn: "Regional Expansion" },
  { page: "about", section: "history", key: "year2026_desc", valueAr: "تبدأ الرابطة خطتها للتوسع الإقليمي بإنشاء فروع في دول أفريقيا Eastern.", valueEn: "The association begins its regional expansion plan with branches in Eastern African countries." },
  { page: "about", section: "cta", key: "title", valueAr: "كن جزءاً من رحلتنا", valueEn: "Be Part of Our Journey" },
  { page: "about", section: "cta", key: "subtitle", valueAr: "انضم إلى آلاف الخريجين المشاركين في بناء مستقبل أفضل", valueEn: "Join thousands of graduates working together to build a better future" },
  { page: "about", section: "cta", key: "button_membership", valueAr: "طلب عضوية", valueEn: "Apply for Membership" },
  { page: "about", section: "cta", key: "button_contact", valueAr: "اتصل بنا", valueEn: "Contact Us" },

  // ═══════════════════════════════════════════════
  // CONTACT PAGE
  // ═══════════════════════════════════════════════
  { page: "contact", section: "hero", key: "title", valueAr: "اتصل بنا", valueEn: "Contact Us" },
  { page: "contact", section: "hero", key: "subtitle", valueAr: "نحن هنا لمساعدتك. تواصل معنا لأي استفسار أو دعم", valueEn: "We are here to help you. Contact us for any inquiry or support" },
  { page: "contact", section: "info", key: "phone_label", valueAr: "الهاتف", valueEn: "Phone" },
  { page: "contact", section: "info", key: "phone_value", valueAr: "+249 11 421 0853", valueEn: "+249 11 421 0853" },
  { page: "contact", section: "info", key: "email_label", valueAr: "البريد الإلكتروني", valueEn: "Email" },
  { page: "contact", section: "info", key: "email_value", valueAr: "aiuagho@gmail.com", valueEn: "aiuagho@gmail.com" },
  { page: "contact", section: "info", key: "address_label", valueAr: "العنوان", valueEn: "Address" },
  { page: "contact", section: "info", key: "address_value", valueAr: "الخرطوم - السودان", valueEn: "Khartoum - Sudan" },
  { page: "contact", section: "info", key: "hours_label", valueAr: "ساعات العمل", valueEn: "Working Hours" },
  { page: "contact", section: "info", key: "hours_value", valueAr: "الأحد - الخميس: 8 ص - 4 م", valueEn: "Sun - Thu: 8 AM - 4 PM" },
  { page: "contact", section: "form", key: "title", valueAr: "أرسل لنا رسالة", valueEn: "Send Us a Message" },
  { page: "contact", section: "map", key: "title", valueAr: "موقعنا", valueEn: "Our Location" },
  { page: "contact", section: "map", key: "open_maps", valueAr: "فتح في خرائط جوجل", valueEn: "Open in Google Maps" },
  { page: "contact", section: "map", key: "map_title", valueAr: "موقع الرابطة على الخريطة", valueEn: "Association Location on Map" },
  { page: "contact", section: "hours_detail", key: "sun_thu", valueAr: "الأحد - الخميس", valueEn: "Sunday - Thursday" },
  { page: "contact", section: "hours_detail", key: "hours_value", valueAr: "8:00 ص - 4:00 م", valueEn: "8:00 AM - 4:00 PM" },
  { page: "contact", section: "hours_detail", key: "fri_sat", valueAr: "الجمعة - السبت", valueEn: "Friday - Saturday" },
  { page: "contact", section: "hours_detail", key: "closed", valueAr: "عطلة", valueEn: "Closed" },

  // ═══════════════════════════════════════════════
  // SERVICES PAGE
  // ═══════════════════════════════════════════════
  { page: "services", section: "hero", key: "title", valueAr: "خدماتنا", valueEn: "Our Services" },
  { page: "services", section: "hero", key: "subtitle", valueAr: "خدمات متكاملة مصممة خصيصاً لخدمة الخريجين ودعم مسيرتهم المهنية", valueEn: "Comprehensive services designed specifically for graduates and their career development" },
  { page: "services", section: "service1", key: "title", valueAr: "خدمات الخريجين", valueEn: "Alumni Services" },
  { page: "services", section: "service1", key: "desc", valueAr: "خدمات متكاملة للخريجين تشمل التسجيل وإصدار الشهادات والتواصل مع الجامعة", valueEn: "Comprehensive services for graduates including registration, certificate issuance, and university liaison" },
  { page: "services", section: "service1", key: "feature1", valueAr: "إصدار شهادة التخرج", valueEn: "Graduation certificate issuance" },
  { page: "services", section: "service1", key: "feature2", valueAr: "تسجيل البيانات في سجل الخريجين", valueEn: "Register in alumni database" },
  { page: "services", section: "service1", key: "feature3", valueAr: "الاستعلام عن السجلات الأكاديمية", valueEn: "Academic records inquiry" },
  { page: "services", section: "service2", key: "title", valueAr: "الإرشاد الأكاديمي", valueEn: "Academic Guidance" },
  { page: "services", section: "service2", key: "desc", valueAr: "برامج إرشادية تهدف إلى دعم الطلاب الحاليين والخريجين في مساراتهم الأكاديمية", valueEn: "Guidance programs aimed at supporting current students and graduates in their academic paths" },
  { page: "services", section: "service2", key: "feature1", valueAr: "إرشاد الطلاب الجدد", valueEn: "New student mentoring" },
  { page: "services", section: "service2", key: "feature2", valueAr: "استشارات الدراسات العليا", valueEn: "Graduate studies consultation" },
  { page: "services", section: "service2", key: "feature3", valueAr: "دعم البحث العلمي", valueEn: "Research support" },
  { page: "services", section: "service3", key: "title", valueAr: "بحث الوظائف", valueEn: "Job Search" },
  { page: "services", section: "service3", key: "desc", valueAr: "منصة متخصصة لربط الخريجين بفرص العمل المناسبة في مختلف القطاعات", valueEn: "Specialized platform connecting graduates with suitable job opportunities across sectors" },
  { page: "services", section: "service3", key: "feature1", valueAr: "نشر السيرة الذاتية", valueEn: "CV posting" },
  { page: "services", section: "service3", key: "feature2", valueAr: "تنبيهات الوظائف", valueEn: "Job alerts" },
  { page: "services", section: "service3", key: "feature3", valueAr: "ورش عمل التوظيف", valueEn: "Interview workshops" },
  { page: "services", section: "service4", key: "title", valueAr: "البرامج التدريبية", valueEn: "Training Programs" },
  { page: "services", section: "service4", key: "desc", valueAr: "برامج تدريبية وورش عمل لتطوير المهارات المهنية والشخصية", valueEn: "Training programs and workshops for developing professional and personal skills" },
  { page: "services", section: "service4", key: "feature1", valueAr: "ورش مهارات القيادة", valueEn: "Leadership skills workshops" },
  { page: "services", section: "service4", key: "feature2", valueAr: "دورات التكنولوجيا", valueEn: "Technology courses" },
  { page: "services", section: "service4", key: "feature3", valueAr: "تدريب على البرامج", valueEn: "Software training" },
  { page: "services", section: "service5", key: "title", valueAr: "استشارات مهنية", valueEn: "Career Consultations" },
  { page: "services", section: "service5", key: "desc", valueAr: "جلسات استشارية مع متخصصين في مجالات مهنية مختلفة", valueEn: "Consultation sessions with specialists in various professional fields" },
  { page: "services", section: "service5", key: "feature1", valueAr: "استشارة مهنية فردية", valueEn: "Individual career consultation" },
  { page: "services", section: "service5", key: "feature2", valueAr: "تقييم المهارات", valueEn: "Skills assessment" },
  { page: "services", section: "service5", key: "feature3", valueAr: "خطة التطوير المهني", valueEn: "Career development plan" },
  { page: "services", section: "service6", key: "title", valueAr: "فعاليات التواصل", valueEn: "Networking Events" },
  { page: "services", section: "service6", key: "desc", valueAr: "فعاليات دورية لتعزيز التواصل المهني بين الخريجين وبناء علاقات قوية", valueEn: "Regular events to enhance professional networking among graduates and build strong relationships" },
  { page: "services", section: "service6", key: "feature1", valueAr: "لقاءات شهرية", valueEn: "Monthly meetups" },
  { page: "services", section: "service6", key: "feature2", valueAr: "مؤتمرات سنوية", valueEn: "Annual conferences" },
  { page: "services", section: "service6", key: "feature3", valueAr: "أحداث خاصة", valueEn: "Special events" },
  { page: "services", section: "cta", key: "title", valueAr: "هل تحتاج مساعدة؟", valueEn: "Need Help?" },
  { page: "services", section: "cta", key: "desc", valueAr: "تواصل معنا للاستفسار عن خدماتنا أو للحصول على دعم شخصي", valueEn: "Contact us to inquire about our services or get personal support" },
  { page: "services", section: "cta", key: "button", valueAr: "تواصل معنا", valueEn: "Contact Us" },

  // ═══════════════════════════════════════════════
  // MEMBERSHIP PAGE
  // ═══════════════════════════════════════════════
  { page: "membership", section: "hero", key: "title", valueAr: "العضوية", valueEn: "Membership" },
  { page: "membership", section: "hero", key: "subtitle", valueAr: "انضم إلى عائلة رابطة خريجي جامعة أفريقيا العالمية واستفد من مزايا حصرية", valueEn: "Join the AIUAG family and benefit from exclusive advantages" },
  { page: "membership", section: "benefits", key: "title", valueAr: "مزايا العضوية", valueEn: "Membership Benefits" },
  { page: "membership", section: "benefit1", key: "title", valueAr: "شبكة خريجين", valueEn: "Alumni Network" },
  { page: "membership", section: "benefit1", key: "desc", valueAr: "تواصل مع آلاف الخريجين من مختلف التخصصات والكليات", valueEn: "Connect with thousands of graduates from various disciplines" },
  { page: "membership", section: "benefit2", key: "title", valueAr: "فرص عمل", valueEn: "Career Opportunities" },
  { page: "membership", section: "benefit2", key: "desc", valueAr: "الوصول إلى فرص العمل والتوظيف الحصرية للأعضاء", valueEn: "Access exclusive job and recruitment opportunities for members" },
  { page: "membership", section: "benefit3", key: "title", valueAr: "برامج تدريبية", valueEn: "Training Programs" },
  { page: "membership", section: "benefit3", key: "desc", valueAr: "استفد من البرامج التدريبية والورش العمل المجانية", valueEn: "Benefit from free training programs and workshops" },
  { page: "membership", section: "benefit4", key: "title", valueAr: "شهادات معتمدة", valueEn: "Certified Credentials" },
  { page: "membership", section: "benefit4", key: "desc", valueAr: "احصل على شهادة عضوية معتمدة من الرابطة", valueEn: "Obtain a membership certificate certified by the association" },
  { page: "membership", section: "benefit5", key: "title", valueAr: "فعاليات حصرية", valueEn: "Exclusive Events" },
  { page: "membership", section: "benefit5", key: "desc", valueAr: "حضور المؤتمرات والندوات بأسعار مميزة", valueEn: "Attend conferences and seminars at special prices" },
  { page: "membership", section: "benefit6", key: "title", valueAr: "دعم مستمر", valueEn: "Ongoing Support" },
  { page: "membership", section: "benefit6", key: "desc", valueAr: "احصل على الدعم والاستشارة المهنية على مدار السنة", valueEn: "Get professional support and consultation year-round" },
  { page: "membership", section: "plans", key: "title", valueAr: "خطط العضوية", valueEn: "Membership Plans" },
  { page: "membership", section: "plan1", key: "name", valueAr: "عضوية سنوية", valueEn: "Annual Membership" },
  { page: "membership", section: "plan1", key: "price", valueAr: "50,000", valueEn: "50,000" },
  { page: "membership", section: "plan1", key: "currency", valueAr: "ج.س", valueEn: "SDG" },
  { page: "membership", section: "plan1", key: "feature1", valueAr: "جميع مزايا العضوية الأساسية", valueEn: "All basic membership benefits" },
  { page: "membership", section: "plan1", key: "feature2", valueAr: "حضور 2 فعالية سنوياً", valueEn: "Attend 2 events per year" },
  { page: "membership", section: "plan1", key: "feature3", valueAr: "نشر سيرة ذاتية في موقع الرابطة", valueEn: "Publish CV on association website" },
  { page: "membership", section: "plan1", key: "feature4", valueAr: "نشرية شهرية", valueEn: "Monthly newsletter" },
  { page: "membership", section: "plan2", key: "name", valueAr: "عضوية مميزة", valueEn: "Premium Membership" },
  { page: "membership", section: "plan2", key: "price", valueAr: "100,000", valueEn: "100,000" },
  { page: "membership", section: "plan2", key: "currency", valueAr: "ج.س", valueEn: "SDG" },
  { page: "membership", section: "plan2", key: "feature1", valueAr: "جميع مزايا العضوية السنوية", valueEn: "All annual membership benefits" },
  { page: "membership", section: "plan2", key: "feature2", valueAr: "حضور غير محدود للفعاليات", valueEn: "Unlimited event attendance" },
  { page: "membership", section: "plan2", key: "feature3", valueAr: "إرشاد أكاديمي شخصي", valueEn: "Personal academic mentoring" },
  { page: "membership", section: "plan2", key: "feature4", valueAr: "استشارات مهنية شهرية", valueEn: "Monthly career consultations" },
  { page: "membership", section: "plan2", key: "feature5", valueAr: "أولوية في البرامج التدريبية", valueEn: "Priority in training programs" },
  { page: "membership", section: "plan3", key: "name", valueAr: "عضوية مدى الحياة", valueEn: "Lifetime Membership" },
  { page: "membership", section: "plan3", key: "price", valueAr: "500,000", valueEn: "500,000" },
  { page: "membership", section: "plan3", key: "currency", valueAr: "ج.س", valueEn: "SDG" },
  { page: "membership", section: "plan3", key: "feature1", valueAr: "جميع مزايا العضوية المميزة", valueEn: "All premium membership benefits" },
  { page: "membership", section: "plan3", key: "feature2", valueAr: "عضوية دائمة بدون تجديد", valueEn: "Permanent membership without renewal" },
  { page: "membership", section: "plan3", key: "feature3", valueAr: "دعوة لكل الفعاليات الكبرى", valueEn: "Invitation to all major events" },
  { page: "membership", section: "plan3", key: "feature4", valueAr: "عضو مجلس استشاري", valueEn: "Advisory council member" },
  { page: "membership", section: "plan3", key: "feature5", valueAr: "شهادة شرفية", valueEn: "Honorary certificate" },
  { page: "membership", section: "plan2", key: "popularBadge", valueAr: "الأكثر طلباً", valueEn: "Most Popular" },
  { page: "membership", section: "plans", key: "applyButton", valueAr: "تقديم طلب", valueEn: "Apply Now" },
  { page: "membership", section: "cta", key: "title", valueAr: "جاهز للانضمام؟", valueEn: "Ready to Join?" },
  { page: "membership", section: "cta", key: "desc", valueAr: "املأ طلب العضوية وانضم إلى آلاف الخريجين المتميزين", valueEn: "Fill out the membership application and join thousands of distinguished graduates" },
  { page: "membership", section: "cta", key: "button", valueAr: "طلب عضوية", valueEn: "Apply for Membership" },

  // ═══════════════════════════════════════════════
  // MEDIA PAGE
  // ═══════════════════════════════════════════════
  { page: "media", section: "hero", key: "title", valueAr: "المركز الإعلامي", valueEn: "Media Center" },
  { page: "media", section: "hero", key: "subtitle", valueAr: "تابع آخر أخبارنا وفعالياتنا من خلال الوسائط المتعددة", valueEn: "Follow our latest news and events through multimedia content" },
  { page: "media", section: "stats", key: "photosLabel", valueAr: "صورة", valueEn: "Photos" },
  { page: "media", section: "stats", key: "videosLabel", valueAr: "فيديو", valueEn: "Videos" },
  { page: "media", section: "stats", key: "publicationsLabel", valueAr: "منشور", valueEn: "Publications" },
  { page: "media", section: "stats", key: "reportsLabel", valueAr: "تقرير", valueEn: "Reports" },
  { page: "media", section: "section1", key: "title", valueAr: "معرض الصور", valueEn: "Photo Gallery" },
  { page: "media", section: "section1", key: "desc", valueAr: "تصفح صور فعالياتنا وأحداثنا والحرم الجامعي", valueEn: "Browse photos of our events, activities, and campus" },
  { page: "media", section: "section2", key: "title", valueAr: "الفيديوهات", valueEn: "Videos" },
  { page: "media", section: "section2", key: "desc", valueAr: "شاهد فيديوهات المؤتمرات والمحاضرات والفعاليات", valueEn: "Watch videos of conferences, lectures, and events" },
  { page: "media", section: "section3", key: "title", valueAr: "المنشورات", valueEn: "Publications" },
  { page: "media", section: "section3", key: "desc", valueAr: "اطلع على المنشورات والتقارير الصادرة عن الرابطة", valueEn: "View publications and reports issued by the association" },
  { page: "media", section: "section4", key: "title", valueAr: "التقارير", valueEn: "Reports" },
  { page: "media", section: "section4", key: "desc", valueAr: "تحميل التقارير السنوية وتقارير الفعاليات", valueEn: "Download annual reports and event reports" },
  { page: "media", section: "section5", key: "title", valueAr: "المنشورات التفاعلية", valueEn: "Interactive Posts" },
  { page: "media", section: "section5", key: "desc", valueAr: "شارك وأتفاعل مع مجتمع الخريجين - نصوص، صور، فيديوهات، تعليقات", valueEn: "Share and interact with the alumni community - text, images, videos, comments" },
  { page: "media", section: "sections", key: "explore", valueAr: "استكشف", valueEn: "Explore" },

  // ═══════════════════════════════════════════════
  // ORGANIZATION PAGE
  // ═══════════════════════════════════════════════
  { page: "organization", section: "hero", key: "title", valueAr: "الهيكل التنظيمي", valueEn: "Organizational Structure" },
  { page: "organization", section: "hero", key: "subtitle", valueAr: "يتكون الهيكل التنظيمي للرابطة من مجلس الإدارة والأمانة العامة واللجان والفروع", valueEn: "The association's organizational structure consists of the Board, Secretariat, Committees, and Branches" },
  { page: "organization", section: "board", key: "title", valueAr: "مجلس الإدارة", valueEn: "Board of Directors" },
  { page: "organization", section: "board", key: "desc", valueAr: "يتكون مجلس الإدارة من أعضاء منتخبين يمثلون الخريجين ويقودون استراتيجيات الرابطة", valueEn: "The Board consists of elected members who represent graduates and lead the association's strategies" },
  { page: "organization", section: "secretariat", key: "title", valueAr: "الأمانة العامة", valueEn: "Secretariat" },
  { page: "organization", section: "secretariat", key: "desc", valueAr: "الأمانة العامة مسؤولة عن الإدارة اليومية والتنسيق بين أعضاء الرابطة واللجان", valueEn: "The Secretariat is responsible for daily management and coordination between members and committees" },
  { page: "organization", section: "committees", key: "title", valueAr: "اللجان", valueEn: "Committees" },
  { page: "organization", section: "committees", key: "desc", valueAr: "لجان متخصصة تعمل في مختلف المجالات لتحقيق أهداف الرابطة وخدمة الخريجين", valueEn: "Specialized committees working in various fields to achieve the association's goals and serve graduates" },
  { page: "organization", section: "branches", key: "title", valueAr: "الفروع", valueEn: "Branches" },
  { page: "organization", section: "branches", key: "desc", valueAr: "فروع الرابطة المنتشرة في مختلف المناطق الجغرافية لتقديم خدمات محلية للخريجين", valueEn: "Association branches spread across various geographic regions to provide local services to graduates" },
  { page: "organization", section: "sections", key: "viewDetails", valueAr: "عرض التفاصيل", valueEn: "View Details" },
  { page: "organization", section: "chart", key: "title", valueAr: "هيكل التنظيمي", valueEn: "Organization Chart" },
  { page: "organization", section: "chart", key: "boardLabel", valueAr: "مجلس الإدارة", valueEn: "Board of Directors" },
  { page: "organization", section: "chart", key: "secretariatLabel", valueAr: "الأمانة العامة", valueEn: "Secretariat" },
  { page: "organization", section: "chart", key: "projects", valueAr: "لجنة المشاريع", valueEn: "Projects" },
  { page: "organization", section: "chart", key: "programs", valueAr: "لجنة البرامج", valueEn: "Programs" },
  { page: "organization", section: "chart", key: "finance", valueAr: "لجنة المالية", valueEn: "Finance" },
  { page: "organization", section: "chart", key: "relations", valueAr: "لجنة العلاقات", valueEn: "Relations" },

  // ═══════════════════════════════════════════════
  // SECRETARIAT PAGE
  // ═══════════════════════════════════════════════
  { page: "secretariat", section: "hero", key: "title", valueAr: "الأمانة العامة", valueEn: "The Secretariat" },
  { page: "secretariat", section: "hero", key: "subtitle", valueAr: "الجهاز التنفيذي الإداري الذي يضمن سير عمل الرابطة بفعالية وكفاءة", valueEn: "The executive administrative body ensuring efficient operations" },
  { page: "secretariat", section: "about", key: "title", valueAr: "نبذة عن الأمانة العامة", valueEn: "About the Secretariat" },
  { page: "secretariat", section: "responsibilities", key: "title", valueAr: "المسؤوليات الرئيسية", valueEn: "Key Responsibilities" },
  { page: "secretariat", section: "departments", key: "title", valueAr: "الأقسام", valueEn: "Departments" },
  { page: "secretariat", section: "contact", key: "title", valueAr: "تواصل مع الأمانة العامة", valueEn: "Contact the Secretariat" },

  // ═══════════════════════════════════════════════
  // FAQ PAGE
  // ═══════════════════════════════════════════════
  { page: "faq", section: "hero", key: "title", valueAr: "الأسئلة الشائعة", valueEn: "Frequently Asked Questions" },
  { page: "faq", section: "hero", key: "subtitle", valueAr: "إجابات لأكثر الأسئلة شيوعاً حول خدماتنا وعضويتنا", valueEn: "Answers to the most common questions about our services and membership" },
  { page: "faq", section: "search", key: "placeholder", valueAr: "ابحث عن سؤال...", valueEn: "Search for a question..." },
  { page: "faq", section: "empty", key: "message", valueAr: "لم يتم العثور على نتائج", valueEn: "No results found" },

  // ═══════════════════════════════════════════════
  // NEWS PAGE
  // ═══════════════════════════════════════════════
  { page: "news", section: "hero", key: "title", valueAr: "الأخبار", valueEn: "News" },
  { page: "news", section: "hero", key: "subtitle", valueAr: "تابع آخر أخبار وفعاليات رابطة خريجي جامعة أفريقيا العالمية", valueEn: "Follow the latest news and events of the Africa International University Alumni Association" },
  { page: "news", section: "hero", key: "badge", valueAr: "آخر الأخبار", valueEn: "Latest News" },
  { page: "news", section: "search", key: "placeholder", valueAr: "ابحث في الأخبار...", valueEn: "Search news..." },
  { page: "news", section: "categories", key: "all", valueAr: "الكل", valueEn: "All" },
  { page: "news", section: "categories", key: "conferences", valueAr: "مؤتمرات", valueEn: "Conferences" },
  { page: "news", section: "categories", key: "forums", valueAr: "مهرجانات", valueEn: "Forums" },
  { page: "news", section: "categories", key: "projects", valueAr: "مشاريع", valueEn: "Projects" },
  { page: "news", section: "categories", key: "workshops", valueAr: "ورش عمل", valueEn: "Workshops" },
  { page: "news", section: "categories", key: "initiatives", valueAr: "مبادرات", valueEn: "Initiatives" },
  { page: "news", section: "categories", key: "partnerships", valueAr: "شراكات", valueEn: "Partnerships" },
  { page: "news", section: "featured", key: "badge", valueAr: "مميز", valueEn: "Featured" },
  { page: "news", section: "newsItem", key: "readMore", valueAr: "اقرأ المزيد", valueEn: "Read More" },

  // ═══════════════════════════════════════════════
  // EVENTS PAGE
  // ═══════════════════════════════════════════════
  { page: "events", section: "hero", key: "title", valueAr: "الأحداث", valueEn: "Events" },
  { page: "events", section: "hero", key: "subtitle", valueAr: "تابع فعالياتنا وأحداثنا القادمة والسابقة", valueEn: "Follow our upcoming and past events and activities" },
  { page: "events", section: "hero", key: "badge", valueAr: "فعالياتنا", valueEn: "Our Events" },
  { page: "events", section: "filters", key: "upcoming", valueAr: "القادمة", valueEn: "Upcoming" },
  { page: "events", section: "filters", key: "past", valueAr: "السابقة", valueEn: "Past" },
  { page: "events", section: "filters", key: "all", valueAr: "الكل", valueEn: "All" },
  { page: "events", section: "calendar", key: "calendarView", valueAr: "عرض التقويم", valueEn: "Calendar View" },
  { page: "events", section: "calendar", key: "daySun", valueAr: "أحد", valueEn: "Sun" },
  { page: "events", section: "calendar", key: "dayMon", valueAr: "إثن", valueEn: "Mon" },
  { page: "events", section: "calendar", key: "dayTue", valueAr: "ثلا", valueEn: "Tue" },
  { page: "events", section: "calendar", key: "dayWed", valueAr: "أرب", valueEn: "Wed" },
  { page: "events", section: "calendar", key: "dayThu", valueAr: "خمي", valueEn: "Thu" },
  { page: "events", section: "calendar", key: "dayFri", valueAr: "جمع", valueEn: "Fri" },
  { page: "events", section: "calendar", key: "daySat", valueAr: "سبت", valueEn: "Sat" },
  { page: "events", section: "upcoming", key: "title", valueAr: "الأحداث القادمة", valueEn: "Upcoming Events" },
  { page: "events", section: "upcoming", key: "statusOngoing", valueAr: "جاري", valueEn: "Ongoing" },
  { page: "events", section: "upcoming", key: "statusComingSoon", valueAr: "قريباً", valueEn: "Coming Soon" },
  { page: "events", section: "upcoming", key: "attendees", valueAr: "مشارك", valueEn: "attendees" },
  { page: "events", section: "past", key: "title", valueAr: "الأحداث السابقة", valueEn: "Past Events" },
  { page: "events", section: "past", key: "statusCancelled", valueAr: "ملغي", valueEn: "Cancelled" },
  { page: "events", section: "past", key: "statusCompleted", valueAr: "منتهي", valueEn: "Completed" },
  { page: "events", section: "months", key: "jan", valueAr: "يناير", valueEn: "Jan" },
  { page: "events", section: "months", key: "feb", valueAr: "فبراير", valueEn: "Feb" },
  { page: "events", section: "months", key: "mar", valueAr: "مارس", valueEn: "Mar" },
  { page: "events", section: "months", key: "apr", valueAr: "أبريل", valueEn: "Apr" },
  { page: "events", section: "months", key: "may", valueAr: "مايو", valueEn: "May" },
  { page: "events", section: "months", key: "jun", valueAr: "يونيو", valueEn: "Jun" },
  { page: "events", section: "months", key: "jul", valueAr: "يوليو", valueEn: "Jul" },
  { page: "events", section: "months", key: "aug", valueAr: "أغسطس", valueEn: "Aug" },
  { page: "events", section: "months", key: "sep", valueAr: "سبتمبر", valueEn: "Sep" },
  { page: "events", section: "months", key: "oct", valueAr: "أكتوبر", valueEn: "Oct" },
  { page: "events", section: "months", key: "nov", valueAr: "نوفمبر", valueEn: "Nov" },
  { page: "events", section: "months", key: "dec", valueAr: "ديسمبر", valueEn: "Dec" },

  // ═══════════════════════════════════════════════
  // PROJECTS PAGE
  // ═══════════════════════════════════════════════
  { page: "projects", section: "hero", key: "title", valueAr: "المشاريع", valueEn: "Projects" },
  { page: "projects", section: "hero", key: "subtitle", valueAr: "نعمل على مشاريع تطويرية تساهم في بناء مستقبل أفضل للجامعة والمجتمع", valueEn: "We work on developmental projects that contribute to building a better future for the university and community" },
  { page: "projects", section: "hero", key: "badge", valueAr: "مشاريعنا", valueEn: "Our Projects" },
  { page: "projects", section: "filters", key: "all", valueAr: "الكل", valueEn: "All" },
  { page: "projects", section: "filters", key: "active", valueAr: "نشط", valueEn: "Active" },
  { page: "projects", section: "filters", key: "completed", valueAr: "مكتمل", valueEn: "Completed" },
  { page: "projects", section: "filters", key: "planning", valueAr: "تخطيط", valueEn: "Planning" },
  { page: "projects", section: "status", key: "active", valueAr: "نشط", valueEn: "Active" },
  { page: "projects", section: "status", key: "completed", valueAr: "مكتمل", valueEn: "Completed" },
  { page: "projects", section: "status", key: "paused", valueAr: "متوقف", valueEn: "Paused" },
  { page: "projects", section: "project", key: "progressLabel", valueAr: "التقدم", valueEn: "Progress" },
  { page: "projects", section: "cta", key: "title", valueAr: "هل لديك فكرة لمشروع جديد؟", valueEn: "Have an idea for a new project?" },
  { page: "projects", section: "cta", key: "desc", valueAr: "شاركنا أفكارك ودعنا نعمل معاً على بناء مشاريع تخدم المجتمع", valueEn: "Share your ideas and let's work together to build projects that serve the community" },
  { page: "projects", section: "cta", key: "button", valueAr: "تواصل معنا", valueEn: "Contact Us" },

  // ═══════════════════════════════════════════════
  // PARTNERS PAGE
  // ═══════════════════════════════════════════════
  { page: "partners", section: "hero", key: "title", valueAr: "الشركاء", valueEn: "Partners" },
  { page: "partners", section: "hero", key: "subtitle", valueAr: "نفخر بشراكتنا مع مؤسسات وشركات رائدة تدعم رسالتنا وأهدافنا", valueEn: "We are proud to partner with leading institutions and companies that support our mission and goals" },
  { page: "partners", section: "hero", key: "badge", valueAr: "شركاؤنا", valueEn: "Our Partners" },
  { page: "partners", section: "filters", key: "all", valueAr: "الكل", valueEn: "All" },
  { page: "partners", section: "filters", key: "partners", valueAr: "شركاء", valueEn: "Partners" },
  { page: "partners", section: "filters", key: "sponsors", valueAr: "رعاة", valueEn: "Sponsors" },
  { page: "partners", section: "filters", key: "supporters", valueAr: "داعمون", valueEn: "Supporters" },
  { page: "partners", section: "empty", key: "message", valueAr: "لا يوجد شركاء حالياً", valueEn: "No partners available" },
  { page: "partners", section: "badge", key: "partner", valueAr: "شريك", valueEn: "Partner" },
  { page: "partners", section: "badge", key: "sponsor", valueAr: "راعي", valueEn: "Sponsor" },
  { page: "partners", section: "badge", key: "supporter", valueAr: "داعم", valueEn: "Supporter" },
  { page: "partners", section: "partner", key: "visitWebsite", valueAr: "زيارة الموقع", valueEn: "Visit Website" },
  { page: "partners", section: "cta", key: "title", valueAr: "كن شريكاً معنا", valueEn: "Become a Partner" },
  { page: "partners", section: "cta", key: "desc", valueAr: "انضم إلى شبكة شركائنا المتنوعين وساهم في دعم رسالة الرابطة وتحقيق أهدافها", valueEn: "Join our diverse network of partners and contribute to supporting the association's mission and goals" },
  { page: "partners", section: "cta", key: "button", valueAr: "تواصل معنا", valueEn: "Contact Us" },

  // ═══════════════════════════════════════════════
  // VOLUNTEER PAGE
  // ═══════════════════════════════════════════════
  { page: "volunteer", section: "hero", key: "title", valueAr: "التطوع معنا", valueEn: "Volunteer With Us" },
  { page: "volunteer", section: "hero", key: "subtitle", valueAr: "كن جزءاً من فريق التطوع وساهم في بناء مستقبل أفضل للخريجين والمجتمع", valueEn: "Be part of the volunteer team and contribute to building a better future" },
  { page: "volunteer", section: "benefits", key: "title", valueAr: "مزايا التطوع", valueEn: "Volunteering Benefits" },
  { page: "volunteer", section: "benefit1", key: "title", valueAr: "إثراء الشخصية", valueEn: "Personal Enrichment" },
  { page: "volunteer", section: "benefit1", key: "desc", valueAr: "تطوير مهارات التواصل والقيادة والعمل الجماعي", valueEn: "Develop communication, leadership, and teamwork skills" },
  { page: "volunteer", section: "benefit2", key: "title", valueAr: "بناء شبكة علاقات", valueEn: "Networking" },
  { page: "volunteer", section: "benefit2", key: "desc", valueAr: "التواصل مع خريجين ومتخصصين من مختلف المجالات", valueEn: "Connect with graduates and professionals from various fields" },
  { page: "volunteer", section: "benefit3", key: "title", valueAr: "خبرة عملية", valueEn: "Practical Experience" },
  { page: "volunteer", section: "benefit3", key: "desc", valueAr: "الحصول على خبرة عملية في إدارة الفعاليات والمشاريع", valueEn: "Gain practical experience in event and project management" },
  { page: "volunteer", section: "benefit4", key: "title", valueAr: "شهادة تطوعية", valueEn: "Volunteer Certificate" },
  { page: "volunteer", section: "benefit4", key: "desc", valueAr: "احصل على شهادة رسمية تعكس جهدك التطوعي", valueEn: "Obtain an official certificate reflecting your volunteer efforts" },
  { page: "volunteer", section: "opportunities", key: "title", valueAr: "فرص التطوع الحالية", valueEn: "Current Volunteer Opportunities" },
  { page: "volunteer", section: "opportunity1", key: "title", valueAr: "تنظيم المؤتمرات", valueEn: "Conference Organization" },
  { page: "volunteer", section: "opportunity1", key: "desc", valueAr: "المساعدة في تنظيم مؤتمر الخريجين السنوي", valueEn: "Help organize the annual alumni conference" },
  { page: "volunteer", section: "opportunity1", key: "deadline", valueAr: "15 يوليو 2026", valueEn: "July 15, 2026" },
  { page: "volunteer", section: "opportunity2", key: "title", valueAr: "إرشاد الطلاب", valueEn: "Student Mentoring" },
  { page: "volunteer", section: "opportunity2", key: "desc", valueAr: "إرشاد الطلاب الحاليين وتوجيههم أكاديمياً", valueEn: "Guide and mentor current students academically" },
  { page: "volunteer", section: "opportunity2", key: "deadline", valueAr: "1 أغسطس 2026", valueEn: "August 1, 2026" },
  { page: "volunteer", section: "opportunity3", key: "title", valueAr: "حملات التبرع", valueEn: "Fundraising Campaigns" },
  { page: "volunteer", section: "opportunity3", key: "desc", valueAr: "المشاركة في حملات جمع التبرعات للصندوق", valueEn: "Participate in fundraising campaigns for the fund" },
  { page: "volunteer", section: "opportunity3", key: "deadline", valueAr: "20 أغسطس 2026", valueEn: "August 20, 2026" },
  { page: "volunteer", section: "opportunity4", key: "title", valueAr: "الدعم الفني", valueEn: "Technical Support" },
  { page: "volunteer", section: "opportunity4", key: "desc", valueAr: "المساعدة في إدارة المنصة الرقمية للرابطة", valueEn: "Help manage the association's digital platform" },
  { page: "volunteer", section: "opportunity4", key: "deadline", valueAr: "10 سبتمبر 2026", valueEn: "September 10, 2026" },
  { page: "volunteer", section: "opportunities", key: "spotsLabel", valueAr: "أماكن متبقية", valueEn: "Spots left" },
  { page: "volunteer", section: "form", key: "title", valueAr: "نموذج طلب التطوع", valueEn: "Volunteer Application Form" },

  // ═══════════════════════════════════════════════
  // DONATIONS PAGE
  // ═══════════════════════════════════════════════
  { page: "donations", section: "hero", key: "title", valueAr: "تبرعاتنا", valueEn: "Our Donations" },
  { page: "donations", section: "hero", key: "subtitle", valueAr: "تبرعك يُحدث فرقاً — ساهم في دعم التعليم والتنمية للخريجين والطلاب", valueEn: "Your donation makes a difference" },
  { page: "donations", section: "form", key: "currencyTitle", valueAr: "اختر العملة", valueEn: "Select Currency" },
  { page: "donations", section: "form", key: "amountTitle", valueAr: "اختر المبلغ", valueEn: "Select Amount" },
  { page: "donations", section: "form", key: "customAmountLabel", valueAr: "مبلغ مخصص", valueEn: "Custom Amount" },
  { page: "donations", section: "form", key: "customAmountPlaceholder", valueAr: "أدخل المبلغ", valueEn: "Enter amount" },
  { page: "donations", section: "form", key: "paymentMethodTitle", valueAr: "طريقة الدفع", valueEn: "Payment Method" },
  { page: "donations", section: "form", key: "localPayment", valueAr: "الدفع المحلي", valueEn: "Local Payment" },
  { page: "donations", section: "form", key: "internationalPayment", valueAr: "الدفع الدولي", valueEn: "International Payment" },
  { page: "donations", section: "form", key: "noGateways", valueAr: "لا توجد بوابات دفع متاحة لهذه العملة", valueEn: "No payment gateways available for this currency" },
  { page: "donations", section: "donorInfo", key: "title", valueAr: "بيانات المتبرع", valueEn: "Donor Information" },
  { page: "donations", section: "donorInfo", key: "fullName", valueAr: "الاسم الكامل", valueEn: "Full Name" },
  { page: "donations", section: "donorInfo", key: "fullNamePlaceholder", valueAr: "محمد أحمد", valueEn: "John Doe" },
  { page: "donations", section: "donorInfo", key: "email", valueAr: "البريد الإلكتروني", valueEn: "Email" },
  { page: "donations", section: "donorInfo", key: "phone", valueAr: "رقم الهاتف", valueEn: "Phone" },
  { page: "donations", section: "donorInfo", key: "phonePlaceholder", valueAr: "+249...", valueEn: "+249..." },
  { page: "donations", section: "donorInfo", key: "country", valueAr: "الدولة", valueEn: "Country" },
  { page: "donations", section: "donorInfo", key: "countryPlaceholder", valueAr: "السودان", valueEn: "Sudan" },
  { page: "donations", section: "donorInfo", key: "messageLabel", valueAr: "رسالة (اختياري)", valueEn: "Message (optional)" },
  { page: "donations", section: "donorInfo", key: "messagePlaceholder", valueAr: "رسالة خاصة...", valueEn: "A personal message..." },
  { page: "donations", section: "donorInfo", key: "anonymousLabel", valueAr: "تبرع مجهول الهوية", valueEn: "Anonymous donation" },
  { page: "donations", section: "summary", key: "amount", valueAr: "المبلغ", valueEn: "Amount" },
  { page: "donations", section: "summary", key: "currency", valueAr: "العملة", valueEn: "Currency" },
  { page: "donations", section: "summary", key: "paymentMethod", valueAr: "طريقة الدفع", valueEn: "Payment Method" },
  { page: "donations", section: "form", key: "termsCheckbox", valueAr: "أوافق على الشروط والأحكام وسياسة الخصوصية", valueEn: "I agree to the Terms and Conditions and Privacy Policy" },
  { page: "donations", section: "form", key: "processing", valueAr: "جاري المعالجة...", valueEn: "Processing..." },
  { page: "donations", section: "form", key: "donateButton", valueAr: "تبرع الآن", valueEn: "Donate Now" },
  { page: "donations", section: "form", key: "securityNote", valueAr: "جميع المعاملات آمنة ومشفرة", valueEn: "All transactions are secure and encrypted" },
  { page: "donations", section: "validation", key: "nameRequired", valueAr: "يرجى إدخال الاسم", valueEn: "Please enter your name" },
  { page: "donations", section: "validation", key: "emailRequired", valueAr: "يرجى إدخال بريد إلكتروني صحيح", valueEn: "Please enter a valid email" },
  { page: "donations", section: "validation", key: "amountRequired", valueAr: "يرجى إدخال مبلغ صحيح", valueEn: "Please enter a valid amount" },
  { page: "donations", section: "validation", key: "paymentRequired", valueAr: "يرجى اختيار طريقة الدفع", valueEn: "Please select a payment method" },
  { page: "donations", section: "validation", key: "termsRequired", valueAr: "يجب قبول الشروط والأحكام", valueEn: "You must accept the terms and conditions" },
  { page: "donations", section: "error", key: "paymentError", valueAr: "حدث خطأ أثناء معالجة الدفع", valueEn: "Payment processing error occurred" },
  { page: "donations", section: "error", key: "connectionError", valueAr: "حدث خطأ أثناء الاتصال بالخادم", valueEn: "Connection error occurred" },

  // ═══════════════════════════════════════════════
  // POSTS PAGE
  // ═══════════════════════════════════════════════
  { page: "posts", section: "hero", key: "title", valueAr: "المشاركات", valueEn: "Posts" },
  { page: "posts", section: "hero", key: "subtitle", valueAr: "آخر المنشورات والتحديثات", valueEn: "Latest posts and updates" },
  { page: "posts", section: "actions", key: "like", valueAr: "إعجاب", valueEn: "Like" },
  { page: "posts", section: "actions", key: "comment", valueAr: "تعليق", valueEn: "Comment" },
  { page: "posts", section: "actions", key: "share", valueAr: "مشاركة", valueEn: "Share" },
  { page: "posts", section: "reactions", key: "label", valueAr: "تفاعل", valueEn: "reactions" },
  { page: "posts", section: "comments", key: "empty", valueAr: "لا توجد تعليقات", valueEn: "No comments yet" },
  { page: "posts", section: "comments", key: "placeholder", valueAr: "اكتب تعليقاً...", valueEn: "Write a comment..." },
  { page: "posts", section: "comments", key: "login", valueAr: "سجل الدخول للتعليق", valueEn: "Log in to comment" },
  { page: "posts", section: "empty", key: "text", valueAr: "لا توجد منشورات بعد", valueEn: "No posts yet" },
  { page: "posts", section: "loadMore", key: "text", valueAr: "تحميل المزيد", valueEn: "Load more" },
  { page: "posts", section: "member", key: "fallback", valueAr: "عضو", valueEn: "Member" },

  // ═══════════════════════════════════════════════
  // RESOURCES PAGE
  // ═══════════════════════════════════════════════
  { page: "resources", section: "hero", key: "title", valueAr: "الموارد", valueEn: "Resources" },
  { page: "resources", section: "hero", key: "subtitle", valueAr: "مصادر مفيدة وتقارير ومنشورات لخدمة الخريجين والمجتمع", valueEn: "Useful sources, reports, and publications for graduates and the community" },
  { page: "resources", section: "categories", key: "annualReports", valueAr: "التقارير السنوية", valueEn: "Annual Reports" },
  { page: "resources", section: "categories", key: "publications", valueAr: "المنشورات", valueEn: "Publications" },
  { page: "resources", section: "categories", key: "research", valueAr: "الأبحاث", valueEn: "Research" },
  { page: "resources", section: "categories", key: "educational", valueAr: "الموارد التعليمية", valueEn: "Educational Resources" },
  { page: "resources", section: "documents", key: "title", valueAr: "المستندات المتاحة", valueEn: "Available Documents" },
  { page: "resources", section: "documents", key: "downloadButton", valueAr: "تحميل", valueEn: "Download" },

  // ═══════════════════════════════════════════════
  // PUBLICATIONS PAGE
  // ═══════════════════════════════════════════════
  { page: "publications", section: "hero", key: "title", valueAr: "المنشورات", valueEn: "Publications" },
  { page: "publications", section: "hero", key: "subtitle", valueAr: "تحميل المنشورات والتقارير والمجلات الصادرة عن الرابطة", valueEn: "Download publications, reports, and magazines issued by the association" },
  { page: "publications", section: "search", key: "placeholder", valueAr: "ابحث عن منشور...", valueEn: "Search publications..." },
  { page: "publications", section: "search", key: "allCategories", valueAr: "الكل", valueEn: "All" },
  { page: "publications", section: "results", key: "countLabel", valueAr: "عدد النتائج:", valueEn: "Results:" },
  { page: "publications", section: "loading", key: "text", valueAr: "جاري التحميل...", valueEn: "Loading..." },
  { page: "publications", section: "empty", key: "message", valueAr: "لا توجد منشورات", valueEn: "No publications found" },
  { page: "publications", section: "publication", key: "downloadButton", valueAr: "تحميل", valueEn: "Download" },
  { page: "publications", section: "publication", key: "notAvailable", valueAr: "غير متاح", valueEn: "N/A" },

  // ═══════════════════════════════════════════════
  // SUPPORT PAGE
  // ═══════════════════════════════════════════════
  { page: "support", section: "hero", key: "title", valueAr: "مركز المساعدة", valueEn: "Help Center" },
  { page: "support", section: "hero", key: "subtitle", valueAr: "كيف يمكننا مساعدتك اليوم؟", valueEn: "How can we help you today?" },
  { page: "support", section: "search", key: "placeholder", valueAr: "ابحث عن مساعدة...", valueEn: "Search for help..." },
  { page: "support", section: "categories", key: "title", valueAr: "اختر موضوعاً", valueEn: "Choose a Topic" },
  { page: "support", section: "category1", key: "title", valueAr: "العضوية", valueEn: "Membership" },
  { page: "support", section: "category1", key: "desc", valueAr: "معلومات عن العضوية والتسجيل والتجديد", valueEn: "Information about membership, registration, and renewal" },
  { page: "support", section: "category1", key: "articlesCount", valueAr: "مقال", valueEn: "articles" },
  { page: "support", section: "category2", key: "title", valueAr: "المدفوعات", valueEn: "Payments" },
  { page: "support", section: "category2", key: "desc", valueAr: "الأسئلة المتعلقة بالتبرعات والدفع", valueEn: "Questions about donations and payments" },
  { page: "support", section: "category3", key: "title", valueAr: "الأحداث", valueEn: "Events" },
  { page: "support", section: "category3", key: "desc", valueAr: "تفاصيل الأحداث والحضور", valueEn: "Event details and attendance" },
  { page: "support", section: "category4", key: "title", valueAr: "الدعم الفني", valueEn: "Technical Support" },
  { page: "support", section: "category4", key: "desc", valueAr: "مساعدة في استخدام الموقع والمنصة", valueEn: "Help with using the website and platform" },
  { page: "support", section: "quickLinks", key: "title", valueAr: "أسئلة سريعة", valueEn: "Quick Questions" },
  { page: "support", section: "quickLink1", key: "title", valueAr: "كيف أسجل في العضوية؟", valueEn: "How do I register for membership?" },
  { page: "support", section: "quickLink1", key: "category", valueAr: "عضوية", valueEn: "Membership" },
  { page: "support", section: "quickLink2", key: "title", valueAr: "كيف أغير كلمة المرور؟", valueEn: "How do I change my password?" },
  { page: "support", section: "quickLink2", key: "category", valueAr: "حسابي", valueEn: "My Account" },
  { page: "support", section: "quickLink3", key: "title", valueAr: "كيف أحجز مقعد في حدث؟", valueEn: "How do I book an event seat?" },
  { page: "support", section: "quickLink3", key: "category", valueAr: "أحداث", valueEn: "Events" },
  { page: "support", section: "quickLink4", key: "title", valueAr: "هل يمكنني استرداد التبرع؟", valueEn: "Can I get a refund on my donation?" },
  { page: "support", section: "quickLink4", key: "category", valueAr: "تبرعات", valueEn: "Donations" },
  { page: "support", section: "quickLink5", key: "title", valueAr: "كيف أحمل شهادتي؟", valueEn: "How do I download my certificate?" },
  { page: "support", section: "quickLink5", key: "category", valueAr: "حسابي", valueEn: "My Account" },
  { page: "support", section: "cta", key: "title", valueAr: "لم تجد الإجابة؟", valueEn: "Didn't Find Your Answer?" },
  { page: "support", section: "cta", key: "desc", valueAr: "فريق الدعم لدينا جاهز لمساعدتك. تواصل معنا وسنرد في أقرب وقت ممكن.", valueEn: "Our support team is ready to help. Contact us and we'll respond as soon as possible." },
  { page: "support", section: "cta", key: "contactButton", valueAr: "تواصل معنا", valueEn: "Contact Us" },
  { page: "support", section: "cta", key: "phone", valueAr: "+249 11 421 0853", valueEn: "+249 11 421 0853" },

  // ═══════════════════════════════════════════════
  // PRIVACY PAGE (section titles only)
  // ═══════════════════════════════════════════════
  { page: "privacy", section: "hero", key: "title", valueAr: "سياسة الخصوصية", valueEn: "Privacy Policy" },
  { page: "privacy", section: "hero", key: "subtitle", valueAr: "نحترم خصوصيتك ونلتزم بحماية معلوماتك الشخصية", valueEn: "We respect your privacy and are committed to protecting your personal information" },
  { page: "privacy", section: "hero", key: "lastUpdated", valueAr: "آخر تحديث: يناير 2026", valueEn: "Last updated: January 2026" },
  { page: "privacy", section: "section1", key: "title", valueAr: "جمع المعلومات", valueEn: "Information Collection" },
  { page: "privacy", section: "section2", key: "title", valueAr: "استخدام المعلومات", valueEn: "Information Usage" },
  { page: "privacy", section: "section3", key: "title", valueAr: "مشاركة المعلومات", valueEn: "Information Sharing" },
  { page: "privacy", section: "section4", key: "title", valueAr: "أمن المعلومات", valueEn: "Data Security" },
  { page: "privacy", section: "section5", key: "title", valueAr: "ملفات تعريف الارتباط", valueEn: "Cookies" },
  { page: "privacy", section: "section6", key: "title", valueAr: "خصوصية الأطفال", valueEn: "Children's Privacy" },
  { page: "privacy", section: "section7", key: "title", valueAr: "التغييرات على سياسة الخصوصية", valueEn: "Changes to Privacy Policy" },
  { page: "privacy", section: "contact", key: "title", valueAr: "لديك أسئلة؟", valueEn: "Have Questions?" },
  { page: "privacy", section: "contact", key: "desc", valueAr: "تواصل معنا لأي استفسار حول سياسة الخصوصية", valueEn: "Contact us for any privacy policy inquiries" },
  { page: "privacy", section: "contact", key: "button", valueAr: "تواصل معنا", valueEn: "Contact Us" },

  // ═══════════════════════════════════════════════
  // TERMS PAGE (section titles only)
  // ═══════════════════════════════════════════════
  { page: "terms", section: "hero", key: "title", valueAr: "الشروط والأحكام", valueEn: "Terms of Service" },
  { page: "terms", section: "hero", key: "subtitle", valueAr: "الشروط والأحكام التي تحكم استخدامك لخدماتنا", valueEn: "The terms and conditions governing your use of our services" },
  { page: "terms", section: "hero", key: "lastUpdated", valueAr: "آخر تحديث: يناير 2026", valueEn: "Last updated: January 2026" },
  { page: "terms", section: "section1", key: "title", valueAr: "المقدمة", valueEn: "Introduction" },
  { page: "terms", section: "section2", key: "title", valueAr: "الأهلية والعضوية", valueEn: "Eligibility & Membership" },
  { page: "terms", section: "section3", key: "title", valueAr: "الحقوق والمسؤوليات", valueEn: "Rights & Responsibilities" },
  { page: "terms", section: "section4", key: "title", valueAr: "القيود والاستثناءات", valueEn: "Limitations & Exclusions" },
  { page: "terms", section: "section5", key: "title", valueAr: "الملكية الفكرية", valueEn: "Intellectual Property" },
  { page: "terms", section: "section6", key: "title", valueAr: "القانون الحاكم", valueEn: "Governing Law" },
  { page: "terms", section: "section7", key: "title", valueAr: "التواصل", valueEn: "Contact" },
  { page: "terms", section: "acceptance", key: "title", valueAr: "القبول بالشروط", valueEn: "Acceptance of Terms" },

  // ═══════════════════════════════════════════════
  // FOOTER
  // ═══════════════════════════════════════════════
  { page: "footer", section: "newsletter", key: "title", valueAr: "اشترك في نشرتنا البريدية", valueEn: "Subscribe to Our Newsletter" },
  { page: "footer", section: "newsletter", key: "desc", valueAr: "احصل على آخر الأخبار والفعاليات", valueEn: "Get the latest news and events" },
  { page: "footer", section: "newsletter", key: "placeholder", valueAr: "بريدك الإلكتروني", valueEn: "Your email" },
  { page: "footer", section: "newsletter", key: "subscribeButton", valueAr: "اشترك", valueEn: "Subscribe" },
  { page: "footer", section: "newsletter", key: "subscribedButton", valueAr: "تم الاشتراك ✓", valueEn: "Subscribed ✓" },
  { page: "footer", section: "about", key: "orgName", valueAr: "رابطة خريجي جامعة أفريقيا العالمية", valueEn: "Association of IUA Graduates" },
  { page: "footer", section: "about", key: "description", valueAr: "رابطة مهنية واجتماعية تخدم مجتمع الخريجين والتنمية", valueEn: "A professional and social association serving the alumni community and development" },
  { page: "footer", section: "quickLinks", key: "title", valueAr: "روابط سريعة", valueEn: "Quick Links" },
  { page: "footer", section: "quickLinks", key: "aboutUs", valueAr: "من نحن", valueEn: "About Us" },
  { page: "footer", section: "quickLinks", key: "board", valueAr: "مجلس الإدارة", valueEn: "Board" },
  { page: "footer", section: "quickLinks", key: "projects", valueAr: "المشاريع", valueEn: "Projects" },
  { page: "footer", section: "quickLinks", key: "news", valueAr: "الأخبار", valueEn: "News" },
  { page: "footer", section: "quickLinks", key: "events", valueAr: "الأحداث", valueEn: "Events" },
  { page: "footer", section: "quickLinks", key: "membership", valueAr: "طلب عضوية", valueEn: "Membership" },
  { page: "footer", section: "services", key: "title", valueAr: "الخدمات", valueEn: "Services" },
  { page: "footer", section: "services", key: "alumniServices", valueAr: "خدمات الخريجين", valueEn: "Alumni Services" },
  { page: "footer", section: "services", key: "volunteer", valueAr: "التطوع", valueEn: "Volunteer" },
  { page: "footer", section: "services", key: "donations", valueAr: "التبرعات", valueEn: "Donations" },
  { page: "footer", section: "services", key: "publications", valueAr: "المنشورات", valueEn: "Publications" },
  { page: "footer", section: "contact", key: "title", valueAr: "تواصل معنا", valueEn: "Contact Us" },
  { page: "footer", section: "contact", key: "address", valueAr: "الخرطوم - السودان", valueEn: "Khartoum - Sudan" },
  { page: "footer", section: "bottom", key: "copyright", valueAr: "جميع الحقوق محفوظة.", valueEn: "All rights reserved." },
  { page: "footer", section: "bottom", key: "privacy", valueAr: "الخصوصية", valueEn: "Privacy" },
  { page: "footer", section: "bottom", key: "terms", valueAr: "الشروط", valueEn: "Terms" },
  { page: "footer", section: "bottom", key: "support", valueAr: "الدعم", valueEn: "Support" },
];

const secretariatMembers = [
  { name: "د. أحمد محمد علي", nameEn: "Dr. Ahmed Mohamed Ali", role: "الأمين العام", roleEn: "Secretary General", bio: "دكتور في إدارة الأعمال، خبرة أكثر من 15 عاماً في الإدارة التنفيذية.", bioEn: "PhD in Business Administration with over 15 years of executive management experience.", phone: "+249114210853", email: "ahmed.ali@aiuag.org", category: "secretariat", order: 1 },
  { name: "أ. فاطمة أحمد حسن", nameEn: "Ms. Fatima Ahmed Hassan", role: "نائبة الأمين العام للشؤون الإدارية", roleEn: "Deputy Secretary General for Administrative Affairs", bio: "ماجستير في الإدارة العامة، متخصصة في الشؤون الإدارية والموارد البشرية.", bioEn: "Master's in Public Administration, specialized in administrative affairs.", phone: "+249114210854", email: "fatima.hassan@aiuag.org", category: "secretariat", order: 2 },
  { name: "أ. محمد عبدالله أحمد", nameEn: "Mr. Mohammed Abdullah Ahmed", role: "نائب الأمين العام للشؤون المالية", roleEn: "Deputy Secretary General for Financial Affairs", bio: "محاسب معتمد، خبرة 12 عاماً في الإدارة المالية والمراجعية.", bioEn: "Certified accountant with 12 years of experience in financial management.", phone: "+249114210855", email: "mohammed.abdullah@aiuag.org", category: "secretariat", order: 3 },
  { name: "د. سارة يوسف إبراهيم", nameEn: "Dr. Sara Youssef Ibrahim", role: "مديرة قسم العضوية", roleEn: "Head of Membership Department", bio: "دكتوراه في العلوم الاجتماعية، مسؤولة عن إدارة شؤون الأعضاء.", bioEn: "PhD in Social Sciences, responsible for managing member affairs.", phone: "+249114210856", email: "sara.ibrahim@aiuag.org", category: "department", order: 4 },
  { name: "أ. خالد عمر المصطفى", nameEn: "Mr. Khalid Omar Mustafa", role: "مدير قسم الإعلام والعلاقات", roleEn: "Head of Media & Relations Department", bio: "بكالوريوس صحافة وإعلام، خبرة واسعة في العلاقات العامة.", bioEn: "Bachelor's in Journalism and Media, extensive experience in public relations.", phone: "+249114210857", email: "khalid.omar@aiuag.org", category: "department", order: 5 },
  { name: "أ. نورة حسين محمد", nameEn: "Ms. Noura Hussein Mohammed", role: "مديرة قسم البرامج والأنشطة", roleEn: "Head of Programs & Activities Department", bio: "ماجستير في إدارة المشاريع، متخصصة في التخطيط والتنفيذ.", bioEn: "Master's in Project Management, specialized in planning and implementation.", phone: "+249114210858", email: "noura.hussein@aiuag.org", category: "department", order: 6 },
  { name: "د. عبدالله علي الصالح", nameEn: "Dr. Abdullah Ali Al-Salah", role: "مستشار الأمين العام للشؤون الأكاديمية", roleEn: "Academic Affairs Advisor", bio: "أستاذ جامعي، خبرة في الإرشاد الأكاديمي وتطوير المناهج.", bioEn: "University professor with experience in academic guidance.", phone: "+249114210859", email: "abdullah.saleh@aiuag.org", category: "secretariat", order: 7 },
  { name: "أ. مريم عثمان أحمد", nameEn: "Ms. Mariam Othman Ahmed", role: "مشرفة على لجنة العضوية", roleEn: "Membership Committee Supervisor", bio: "خبرة 8 سنوات في إدارة العضوية والتحقق من البيانات.", bioEn: "8 years of experience in membership management.", phone: "+249114210860", email: "mariam.othman@aiuag.org", category: "committee", order: 8 },
];

export async function POST() {
  try {
    let pageCount = 0;
    for (const item of pageContents) {
      try {
        await prisma.pageContent.upsert({
          where: { page_section_key: { page: item.page, section: item.section, key: item.key } },
          update: { valueAr: item.valueAr, valueEn: item.valueEn },
          create: item,
        });
        pageCount++;
      } catch { /* skip duplicates */ }
    }

    let memberCount = 0;
    for (const member of secretariatMembers) {
      const existing = await prisma.secretariatMember.findFirst({ where: { name: member.name } });
      if (!existing) {
        await prisma.secretariatMember.create({ data: member });
        memberCount++;
      }
    }

    return NextResponse.json({ success: true, pageCount, memberCount, totalPages: [...new Set(pageContents.map(c => c.page))].length });
  } catch (error) {
    return NextResponse.json({ error: "Seed failed" }, { status: 500 });
  }
}
